// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from 'F:/Nim UI/my-next-dumi-docs/node_modules/dumi/theme-default/slots/SearchBar/index.js';
export * from 'F:/Nim UI/my-next-dumi-docs/node_modules/dumi/theme-default/slots/SearchBar/index.js';
