// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { frontmatter as fm0, toc as t0 } from 'F:/Nim UI/my-next-dumi-docs/docs/guide/button.md?type=frontmatter';
import { demoIndex as dmi0 } from 'F:/Nim UI/my-next-dumi-docs/docs/guide/button.md?type=demo-index';
import { frontmatter as fm1, toc as t1 } from 'F:/Nim UI/my-next-dumi-docs/docs/guide/index.md?type=frontmatter';
import { demoIndex as dmi1 } from 'F:/Nim UI/my-next-dumi-docs/docs/guide/index.md?type=demo-index';
import { frontmatter as fm2, toc as t2 } from 'F:/Nim UI/my-next-dumi-docs/docs/index.md?type=frontmatter';
import { demoIndex as dmi2 } from 'F:/Nim UI/my-next-dumi-docs/docs/index.md?type=demo-index';

export const filesMeta = {
  'docs/guide/button': {
    frontmatter: fm0,
    toc: t0,
    demoIndex: dmi0,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'F:/Nim UI/my-next-dumi-docs/docs/guide/button.md?type=text'),
  },
  'docs/guide/index': {
    frontmatter: fm1,
    toc: t1,
    demoIndex: dmi1,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'F:/Nim UI/my-next-dumi-docs/docs/guide/index.md?type=text'),
  },
  'docs/index': {
    frontmatter: fm2,
    toc: t2,
    demoIndex: dmi2,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'F:/Nim UI/my-next-dumi-docs/docs/index.md?type=text'),
  },
}

export { tabs as tabsMeta } from './tabs';
